/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personalabteilung;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author kraft
 */
public class Personalmaske extends javax.swing.JFrame {

    /**
     * Creates new form Personalmaske
     */
    private ArrayList<Person> mitarbeiterObjectList = new ArrayList<>();
    private DefaultListModel mitarbeiterModel = new DefaultListModel();
    
    public Personalmaske() {
        initComponents();
        anzeigeMitarbeiterList.setModel(mitarbeiterModel);
        anzeigeMitarbeiterList.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        neueMitarbeiterLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameEingabe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        berufeAuswahlList = new javax.swing.JList<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        speichernButton = new javax.swing.JButton();
        berufLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        anzeigeMitarbeiterList = new javax.swing.JList<>();
        berufCheckedLabel = new javax.swing.JLabel();
        vornameLabel = new javax.swing.JLabel();
        vornameEingabe = new javax.swing.JTextField();
        bdayLabel = new javax.swing.JLabel();
        bdayEingabe = new javax.swing.JTextField();
        sucheButton = new javax.swing.JButton();
        suchEingabe = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        neueMitarbeiterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        neueMitarbeiterLabel.setText("Neue Mitarbeiter");

        nameLabel.setText("Name:");

        berufeAuswahlList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Manager", "Mitarbeiter", "Hilfskraft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        berufeAuswahlList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                berufeAuswahlListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(berufeAuswahlList);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setInheritsPopupMenu(true);
        jRadioButton1.setLabel("Männlich");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setLabel("Weiblich");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setLabel("Divers");

        speichernButton.setLabel("Speichern");
        speichernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichernButtonActionPerformed(evt);
            }
        });

        berufLabel.setText("Beruf:");

        anzeigeMitarbeiterList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                anzeigeMitarbeiterListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(anzeigeMitarbeiterList);

        berufCheckedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        berufCheckedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        vornameLabel.setText("Vorname:");

        bdayLabel.setText("Geburtsdatum:");

        sucheButton.setText("Suchen");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(berufLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vornameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neueMitarbeiterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(nameEingabe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(vornameEingabe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bdayEingabe))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(berufCheckedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(speichernButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(suchEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sucheButton)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(neueMitarbeiterLabel)
                .addGap(27, 27, 27)
                .addComponent(berufCheckedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdayLabel)
                            .addComponent(bdayEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vornameLabel)
                                .addComponent(vornameEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(berufLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(speichernButton)
                                    .addComponent(sucheButton)
                                    .addComponent(suchEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private JRadioButton getSelectedRadioButton() throws CustomException {
        
        Enumeration<AbstractButton> allRadioButtons=this.buttonGroup1.getElements();
            while (allRadioButtons.hasMoreElements()) {
                JRadioButton oneRadioButton = (JRadioButton) allRadioButtons.nextElement();
                if (oneRadioButton.isSelected()) {
                    return oneRadioButton;
                }
            }
        throw new CustomException("Bitte wählen Sie ein Geschlecht aus.");
    }
    
    private String getSelectedBeruf() throws CustomException {
        
        List<String> berufe = berufeAuswahlList.getSelectedValuesList();
        
        if(berufe.isEmpty()) {
            throw new CustomException("Bitte wählen Sie ein Beruf aus.");
        }
        if(berufe.size()>1) {
            throw new CustomException("Bitte wählen Sie nur einen Beruf aus.");
        }
        return berufe.get(0);
    }
    
    private String getTypedInName() throws CustomException {
        String name = "";
        try {
            name = nameEingabe.getText();
        } catch(NullPointerException e) {
            throw new CustomException("Bitte Namen eingeben.");
        }
        if (name.length()==0) {
            throw new CustomException("Bitte Namen eingeben.");
        }
        return name;
    }
    
    private String getTypedInVorname() throws CustomException {
        String vorName = "";
        try {
            vorName = vornameEingabe.getText();
        } catch(NullPointerException e) {
            throw new CustomException("Bitte Vornamen eingeben.");
        }
        if (vorName.length()==0) {
            throw new CustomException("Bitte Vornamen eingeben.");
        }
        return vorName;
    }
    
    private String getTypedInBday() throws CustomException {
        
        String bday = "";
        try {
            bday = bdayEingabe.getText();
        } catch(NullPointerException e) {
            throw new CustomException("Bitte Geburtsdatum eingeben.");
        }
        if (bday.length()==0) {
            throw new CustomException("Bitte Geburtsdatum eingeben.");
        }
        return bday;
    }
    
    private String getTypedInSuche() throws CustomException {
        
        String suchString = "";
        try {
            suchString = suchEingabe.getText();
        } catch(NullPointerException e) {
            throw new CustomException("Bitte Geburtsdatum eingeben.");
        }
        if (suchString.length()==0) {
            throw new CustomException("Bitte Geburtsdatum eingeben.");
        }
        return suchString;
    }
    
    private String findMitarbeiter(String attribut) {
        for(Person p: mitarbeiterObjectList) {
            // Müsste schauen wie ich bequem durch die Attributwerte loope
        }
        // return toString von Person
    }
    
    private void speichernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichernButtonActionPerformed
        
        String meldung = "";
        
        try {
            String vorname = this.getTypedInVorname();
            String name = this.getTypedInName();
            String bday = this.getTypedInBday();
            String beruf = this.getSelectedBeruf();
            JRadioButton selectedRadioButton = this.getSelectedRadioButton();
            Person neuePerson = new Person(vorname, name, beruf, selectedRadioButton.getText(), bday);
            mitarbeiterObjectList.add(neuePerson);
            mitarbeiterModel.addElement(name);
        }
        catch(CustomException e) {
            meldung += e.getMessage()+"\n";
        } 
        finally {
            if(meldung.length()>0) {
                JOptionPane.showMessageDialog(null, meldung, null, JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, this.berufeAuswahlList.getSelectedValue()+ " " + nameEingabe.getText() + " erfolgreich gespeichert!", null, JOptionPane.INFORMATION_MESSAGE);
                anzeigeMitarbeiterList.setVisible(false);
                buttonGroup1.clearSelection();
                nameEingabe.setText("");
                vornameEingabe.setText("");
                bdayEingabe.setText("");
                berufeAuswahlList.clearSelection();
            }
        }
    }//GEN-LAST:event_speichernButtonActionPerformed

    private void anzeigeMitarbeiterListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_anzeigeMitarbeiterListValueChanged
        
    }//GEN-LAST:event_anzeigeMitarbeiterListValueChanged

    private void berufeAuswahlListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_berufeAuswahlListValueChanged
        anzeigeMitarbeiterList.setVisible(true);
        berufCheckedLabel.setText(berufeAuswahlList.getSelectedValue());
        mitarbeiterModel.clear();
        
        for (Person p: mitarbeiterObjectList) {
            if(p.getBeruf().equals(berufCheckedLabel.getText())){
                mitarbeiterModel.addElement(p.getName());
            }
        }
    }//GEN-LAST:event_berufeAuswahlListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalmaske().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> anzeigeMitarbeiterList;
    private javax.swing.JTextField bdayEingabe;
    private javax.swing.JLabel bdayLabel;
    private javax.swing.JLabel berufCheckedLabel;
    private javax.swing.JLabel berufLabel;
    private javax.swing.JList<String> berufeAuswahlList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameEingabe;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel neueMitarbeiterLabel;
    private javax.swing.JButton speichernButton;
    private javax.swing.JTextField suchEingabe;
    private javax.swing.JButton sucheButton;
    private javax.swing.JTextField vornameEingabe;
    private javax.swing.JLabel vornameLabel;
    // End of variables declaration//GEN-END:variables
}
