/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personalabteilung;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author kraft
 */
public class Personalmaske extends javax.swing.JFrame {

    /**
     * Creates new form Personalmaske
     */
    private ArrayList<Person> mitarbeiterObjectList = new ArrayList<>();
    private DefaultListModel mitarbeiterModel = new DefaultListModel();
    
    public Personalmaske() {
        initComponents();
        anzeigeMitarbeiterList.setModel(mitarbeiterModel);
        anzeigeMitarbeiterList.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        neueMitarbeiterLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameEingabe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        berufeAuswahlList = new javax.swing.JList<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        speichernButton = new javax.swing.JButton();
        berufLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        anzeigeMitarbeiterList = new javax.swing.JList<>();
        berufCheckedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        neueMitarbeiterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        neueMitarbeiterLabel.setText("Neue Mitarbeiter");

        nameLabel.setText("Name:");

        berufeAuswahlList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Manager", "Mitarbeiter", "Hilfskraft" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        berufeAuswahlList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                berufeAuswahlListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(berufeAuswahlList);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setInheritsPopupMenu(true);
        jRadioButton1.setLabel("Männlich");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setLabel("Weiblich");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setLabel("Divers");

        speichernButton.setLabel("Speichern");
        speichernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichernButtonActionPerformed(evt);
            }
        });

        berufLabel.setText("Beruf:");

        anzeigeMitarbeiterList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                anzeigeMitarbeiterListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(anzeigeMitarbeiterList);

        berufCheckedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        berufCheckedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speichernButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(berufLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neueMitarbeiterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(berufCheckedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(neueMitarbeiterLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(berufCheckedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameEingabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(berufLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(speichernButton)
                .addGap(55, 55, 55))
        );

        jScrollPane2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private JRadioButton getSelectedRadioButton() throws RadioButtonException {
        
        Enumeration<AbstractButton> allRadioButtons=this.buttonGroup1.getElements();
            while (allRadioButtons.hasMoreElements()) {
                JRadioButton oneRadioButton = (JRadioButton) allRadioButtons.nextElement();
                if (oneRadioButton.isSelected()) {
                    return oneRadioButton;
                }
            }
        throw new RadioButtonException("Bitte wählen Sie ein Geschlecht aus.");
    }
    
    private String getSelectedBeruf() throws ListSelectException {
        
        List<String> berufe = berufeAuswahlList.getSelectedValuesList();
        
        if(berufe.isEmpty()) {
            throw new ListSelectException("Bitte wählen Sie ein Beruf aus.");
        }
        if(berufe.size()>1) {
            throw new ListSelectException("Bitte wählen Sie nur einen Beruf aus.");
        }
        return berufe.get(0);
    }
    
    private String getTypedInName() throws NameInputException {
        String name = "";
        try {
            name = nameEingabe.getText();
        } catch(NullPointerException e) {
            throw new NameInputException("Bitte Namen eingeben.");
        }
        if (name.length()==0) {
            throw new NameInputException("Bitte Namen eingeben.");
        }
        return name;
    }
    
    private void speichernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichernButtonActionPerformed
        
        String meldung = "";
        
        try {
            JRadioButton selectedRadioButton = this.getSelectedRadioButton();
            String beruf = this.getSelectedBeruf();
            String name = this.getTypedInName();
            Person neuePerson = new Person(name, beruf, selectedRadioButton.getText());
            mitarbeiterObjectList.add(neuePerson);
            mitarbeiterModel.addElement(name);
        }
        catch(NameInputException | ListSelectException| RadioButtonException e) {
            meldung += e.getMessage()+"\n";
        } 
        finally {
            if(meldung.length()>0) {
                JOptionPane.showMessageDialog(null, meldung, null, JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, this.berufeAuswahlList.getSelectedValue()+ " " + nameEingabe.getText() + " erfolgreich gespeichert!", null, JOptionPane.INFORMATION_MESSAGE);
                anzeigeMitarbeiterList.setVisible(false);
                buttonGroup1.clearSelection();
                nameEingabe.setText("");
                berufeAuswahlList.clearSelection();
            }
        }
    }//GEN-LAST:event_speichernButtonActionPerformed

    private void anzeigeMitarbeiterListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_anzeigeMitarbeiterListValueChanged
        
    }//GEN-LAST:event_anzeigeMitarbeiterListValueChanged

    private void berufeAuswahlListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_berufeAuswahlListValueChanged
        anzeigeMitarbeiterList.setVisible(true);
        berufCheckedLabel.setText(berufeAuswahlList.getSelectedValue());
        mitarbeiterModel.clear();
        
        for (Person p: mitarbeiterObjectList) {
            if(p.getBeruf().equals(berufCheckedLabel.getText())){
                mitarbeiterModel.addElement(p.getName());
            }
        }
    }//GEN-LAST:event_berufeAuswahlListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalmaske.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalmaske().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> anzeigeMitarbeiterList;
    private javax.swing.JLabel berufCheckedLabel;
    private javax.swing.JLabel berufLabel;
    private javax.swing.JList<String> berufeAuswahlList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameEingabe;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel neueMitarbeiterLabel;
    private javax.swing.JButton speichernButton;
    // End of variables declaration//GEN-END:variables
}
